// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oalvdwqpjihwduqsdbyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hbHZkd3Fwamlod2R1cXNkYnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTk1MDAsImV4cCI6MjA1ODc5NTUwMH0.AGpKLP6qYIT9Cp-FaEd8oQa1YL2DEuHg6CAaeUVTjz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);